Windows Support
Tsche/repr pull request #6
Opened 2023-11-16 23:19 UTC by 8ightfold

You know what this is...

2023-11-18 07:09 UTC, Tsche requested changes

2023-11-18 07:09 UTC, Tsche commented on include/librepr/type/detail/undecorate.h
> +#define M2B_CAST(b, m) [](auto* __ptr) { \
does this need to be a macro?

2023-11-18 07:09 UTC, Tsche commented on include/librepr/type/detail/undecorate.h
> +    }
should probably place a `std::unreachable();` here

2023-11-18 07:09 UTC, Tsche commented on include/librepr/type/name.h
> +    static volatile auto _ = ty.name();
oof. Can you give it some name to stop clang-tidy from complaining though? :P

Minimum length is set to 3 characters I think

2023-11-18 07:09 UTC, Tsche commented on include/librepr/type_info.h
> +using StrFormatter = REPR_FORMAT_NS::formatter<std::string, CharT>;
this should probably be in the `librepr::detail` namespace

2023-11-19 19:04 UTC, 8ightfold commented on include/librepr/type/detail/denoise.h
> +  std::string_view to_sv(SymToken tok) const {
? Not sure what this means... I cant move this into the token class

2023-11-19 19:05 UTC, 8ightfold commented on include/librepr/type/detail/denoise.h
> +  static REPR_MINLINE bool isIdent(char c) {
Yeah it was just 4am and I couldn't think of a name

2023-11-19 19:06 UTC, 8ightfold commented on include/librepr/type/detail/denoise.h
> +  static REPR_MINLINE bool isWord(char c) {
Word like regex's ``\w``

2023-11-19 19:08 UTC, 8ightfold commented on include/librepr/type/detail/denoise.h
> +    return (c >= 'A' && c <= 'Z') ||
Nope, wouldn't be legal

2023-11-19 19:08 UTC, 8ightfold commented on include/librepr/type/detail/undecorate.h
> +#define M2B_CAST(b, m) [](auto* __ptr) { \
It's easier to follow imo

2023-11-19 19:14 UTC, 8ightfold commented on include/librepr/util/strings.h
> +#define REPR_STRSIZE(...) ::librepr::detail::strsize(__VA_ARGS__)
commas

2023-11-19 19:17 UTC, 8ightfold commented on include/librepr/type/detail/denoise.h
> +  SymToken llast;
lex

2023-11-20 02:59 UTC, Tsche commented on include/librepr/util/strings.h
> +#define REPR_STRSIZE(...) ::librepr::detail::strsize(__VA_ARGS__)
wdym? Does this need to be a macro?

2023-11-20 02:59 UTC, Tsche commented on include/librepr/type/detail/denoise.h
> +  SymToken llast;
Would `current_lexeme` and `last_lexeme` be more fitting then?

2023-11-20 02:59 UTC, Tsche commented on include/librepr/type/detail/denoise.h
> +  std::string_view to_sv(SymToken tok) const {
Oh my bad, I think I misread this one.

2023-11-20 02:59 UTC, Tsche commented on include/librepr/type/detail/denoise.h
> +  static REPR_MINLINE bool isWord(char c) {
Okay, fair enough. I'd prefer snake case (`is_word`) though :)

2023-11-20 05:00 UTC, 8ightfold commented on include/librepr/type/detail/denoise.h
> +  SymToken llast;
Sure that would work

2023-11-20 05:02 UTC, 8ightfold commented on include/librepr/util/strings.h
> +#define REPR_STRSIZE(...) ::librepr::detail::strsize(__VA_ARGS__)
Probably not :P

2024-01-11 03:04 UTC, Tsche approved these changes

2024-01-11 03:11 UTC, merged